-- Insert Data into Customers Table
INSERT INTO Customers (Name, Email, Phone, Address, City, State) VALUES
('John Doe', 'johndoe@example.com', '555-1234', '123 Main St', 'Springfield', 'Illinois'),
('Jane Smith', 'janesmith@example.com', '555-5678', '456 Elm St', 'Metropolis', 'New York'),
('Robert Johnson', 'robertj@example.com', '555-8765', '789 Oak St', 'Gotham', 'New Jersey'),
('Emily Davis', 'emilyd@example.com', '555-2345', '321 Maple St', 'Star City', 'California'),
('Michael Brown', 'michaelb@example.com', '555-3456', '654 Pine St', 'Central City', 'Ohio'),
('Jessica Wilson', 'jessicaw@example.com', '555-4567', '987 Birch St', 'Smallville', 'Kansas'),
('Daniel Moore', 'danielm@example.com', '555-5679', '135 Walnut St', 'Coast City', 'Oregon'),
('Sophia Taylor', 'sophiat@example.com', '555-6789', '246 Cherry St', 'Keystone City', 'Pennsylvania'),
('David Anderson', 'davidanderson@example.com', '555-7890', '357 Cedar St', 'Hub City', 'South Dakota'),
('Olivia Thomas', 'oliviathomas@example.com', '555-8901', '468 Spruce St', 'Ivy Town', 'Connecticut'),
('William Jackson', 'williamjackson@example.com', '555-9012', '579 Ash St', 'Fawcett City', 'Missouri'),
('Ava White', 'avawhite@example.com', '555-0123', '680 Alder St', 'Midway City', 'Michigan'),
('James Harris', 'jamesharris@example.com', '555-1230', '791 Fir St', 'Happy Harbor', 'Maine'),
('Mia Martin', 'miamartin@example.com', '555-2340', '892 Cypress St', 'Ivy City', 'Virginia'),
('Benjamin Martinez', 'benjaminmartinez@example.com', '555-3450', '903 Poplar St', 'Blüdhaven', 'Delaware'),
('Charlotte Robinson', 'charlotterobinson@example.com', '555-4560', '114 Dogwood St', 'Gateway City', 'Georgia'),
('Lucas Clark', 'lucasclark@example.com', '555-5670', '225 Palm St', 'Opal City', 'Texas'),
('Amelia Lewis', 'amelialewis@example.com', '555-6780', '336 Redwood St', 'St. Roch', 'Louisiana'),
('Mason Walker', 'masonwalker@example.com', '555-7891', '447 Sequoia St', 'New Carthage', 'Nevada'),
('Harper Hall', 'harperhall@example.com', '555-8902', '558 Juniper St', 'Ivy Town', 'Connecticut'),
('Ethan Allen', 'ethanallen@example.com', '555-9013', '669 Sycamore St', 'Gateway City', 'Georgia'),
('Isabella Young', 'isabellayoung@example.com', '555-0124', '770 Larch St', 'Blüdhaven', 'Delaware'),
('Alexander King', 'alexanderking@example.com', '555-1231', '881 Willow St', 'Fawcett City', 'Missouri'),
('Avery Wright', 'averywright@example.com', '555-2341', '992 Laurel St', 'Coast City', 'Oregon'),
('Sophia Lee', 'sophialee@example.com', '555-3451', '103 Hickory St', 'Hub City', 'South Dakota');
